#!/bin/bash

{
printf "\e[0;34mInstalling required packages\e[0m\n"
yum install -y php php-openssl php-mysql php-curl httpd mariadb mariadb-server git expect

printf "\e[0;34mEnabling MySQL\e[0m\n"
systemctl enable mariadb.service
systemctl start mariadb.service
printf "\e[0;34mEnabling apache2\e[0m\n"
systemctl enable httpd.service
systemctl start httpd.service

printf "\e[0;34mInstalling composer\e[0m\n"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

printf "\e[0;34mDownloading paypal sample app\e[0m\n"
cd /var/www/html/
git clone https://github.com/paypal/rest-api-sample-app-php.git
mv rest-api-sample-app-php/* ./ # assuming this should be the root of the webserver
rm -rf rest-api-sample-app-php

printf "\e[0;34mRunning composer update\e[0m\n"
composer update

printf "\e[0;34mGenerating MySQL passwords\e[0m\n"
mysql_root_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c16)
export mysql_root_password # because expect requires variables to be global
mysql_paypaluser_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c16)

printf "\e[0;34mSetting up MySQL\e[0m\n"
/usr/bin/expect -c '
set timeout 2

log_user 0 # hide output, add option for -v?
spawn mysql_secure_installation
expect "Enter current password for root (enter for none): "
send "\r"
expect "Change the root password? \[Y/n\] "
send "Y\r"
expect "New password: "
send "$env(mysql_root_password)\r"
expect "Re-enter new password: "
send "$env(mysql_root_password)\r"
expect "Remove anonymous users? \[Y/n\] "
send "Y\r"
expect "Disallow root login remotely? \[Y/n\] "
send "Y\r"
expect "Remove test database and access to it? \[Y/n\] "
send "Y\r"
expect "Reload privilege tables now? \[Y/n\] "
send "Y\r" '

mysql -uroot -p"$mysql_root_password" -e "create database paypal_pizza_app;"
mysql -uroot -p"$mysql_root_password" -e "grant all privileges on paypal_pizza_app.* to paypal_user@localhost identified by '$mysql_paypaluser_password';"
mysql -uroot -p"$mysql_root_password" paypal_pizza_app < install/db.sql

printf "\e[0;34mSetting MySQL login details within app config\e[0m\n"
sed -i "s/'MYSQL_USERNAME', 'root'/'MYSQL_USERNAME', 'paypal_user'/; s/'MYSQL_PASSWORD', 'root'/'MYSQL_PASSWORD', '$mysql_paypaluser_password'/" /var/www/html/app/bootstrap.php

printf "\e[0;34mSetting firewall rules\e[0m\n"
printf "\e[0;34mallow http traffic: "
firewall-cmd --zone=public --add-service=http --permanent
printf "\e[0;34mallow https traffic: "
firewall-cmd --zone=public --add-service=https --permanent
printf "\e[0;34mReloading firewall: "
firewall-cmd --reload

printf "\e[0;34mmysql root password is: $mysql_root_password\e[0m\n"
printf "\e[0;34mmysql application user password is: $mysql_paypaluser_password\e[0m\n"

unset mysql_root_password # so this isn't just hanging around in the terminal session
} | tee setup.log 
