#!/usr/bin/expect -f

set timeout 2
set arg1 [lindex $argv 0]

log_user 0 # hide output, add option for -v?
spawn mysql_secure_installation
expect "Enter current password for root (enter for none): "
send "\r"
expect "Change the root password? \[Y/n\] "
send "Y\r"
expect "New password: "
send "$arg1\r"
expect "Re-enter new password: "
send "$arg1\r"
expect "Remove anonymous users? \[Y/n\] "
send "Y\r"
expect "Disallow root login remotely? \[Y/n\] "
send "Y\r"
expect "Remove test database and access to it? \[Y/n\] "
send "Y\r"
expect "Reload privilege tables now? \[Y/n\] "
send "Y\r"
